### ISSUE TITLE
Release Build No Mediator Connection

### ISSUE THREAD

**Issue by matrwolff33** [openwallet-foundation/bifold-wallet#144]
Hello,
I am currently trying to create a release build so that I may distribute the APK amongst our team members for testing with various solutions / demos that we have. When running in debug / development I have no issues and am able to form the connection with the mediator and all seems well. But when creating an apk using `./gradlew assembleRelease` the connection is never formed and there is an exception that is logged out that I don't see in any other builds. Curious if anyone has run into this or might have an idea of what is going on? 

`
2021-11-19 16:55:25.033 27898-27940/com.ariesbifold W/CipherStorageBase: StrongBox security storage is not available.
    java.security.ProviderException: Failed to generate key pair.
        at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:620)
        at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:545)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
        at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.generateKey(CipherStorageKeystoreRsaEcb.java:256)
        at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateStrongBoxSecurityKey(CipherStorageBase.java:444)
        at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:391)
        at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(KeychainModule.java:173)
        at com.oblador.keychain.KeychainModule.lambda$DYujhqpjRgfFQ_gyuwMwyxxqDlk(Unknown Source:0)
        at com.oblador.keychain.-$$Lambda$KeychainModule$DYujhqpjRgfFQ_gyuwMwyxxqDlk.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.security.KeyStoreException: Unsupported key size
        at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
        at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
        at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:145)
        at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:587)
`

**Comment by jleach** [comment]
As per todays Bifold UG/WG call we're closing stale issues. Please re-open if you feel strongly its still an issue and relevent.

**Comment by jleach** [comment]
Closing. Looks like PR#150 may have addressed this.
