### ISSUE TITLE
Error using biometrics if no fingerprint is configured

### ISSUE THREAD

**Issue by thiagoromanos** [openwallet-foundation/bifold-wallet#442]
When using the app for the first time on a device which no fingerprint were configured, the "Create PIN" button does nothing. If I configure at least one fingerprint, the button works fine.
There was no log on Metro console regarding this behavior, but I noticed running `adb logcat` that there was errors in android code. Here's what I got from logcat:

```09-14 10:51:59.621  4975  5035 E CipherStorageBase: Regular security storage is not available.
09-14 10:51:59.621  4975  5035 E CipherStorageBase: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: Secure lock screen must be enabled to create keys requiring user authentication
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize(AndroidKeyStoreKeyPairGeneratorSpi.java:349)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:697)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:438)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.generateKey(CipherStorageKeystoreRsaEcb.java:255)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateRegularSecurityKey(CipherStorageBase.java:445)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:421)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.innerEncryptedCredentials(CipherStorageKeystoreRsaEcb.java:197)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.encrypt(CipherStorageKeystoreRsaEcb.java:70)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.KeychainModule.setGenericPassword(KeychainModule.java:223)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.oblador.keychain.KeychainModule.setGenericPasswordForOptions(KeychainModule.java:252)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at java.lang.reflect.Method.invoke(Native Method)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.os.Handler.handleCallback(Handler.java:873)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.os.Looper.loop(Looper.java:193)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at java.lang.Thread.run(Thread.java:764)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: Caused by: java.lang.IllegalStateException: Secure lock screen must be enabled to create keys requiring user authentication
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.security.keystore.KeymasterUtils.getRootSid(KeymasterUtils.java:222)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.security.keystore.KeymasterUtils.addUserAuthArgs(KeymasterUtils.java:164)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize(AndroidKeyStoreKeyPairGeneratorSpi.java:347)
09-14 10:51:59.621  4975  5035 E CipherStorageBase: 	... 19 more
09-14 10:51:59.621  4975  5035 E RNKeychainManager: Unknown error: java.lang.IllegalStateException: Secure lock screen must be enabled to create keys requiring user authentication
09-14 10:51:59.621  4975  5035 E RNKeychainManager: com.oblador.keychain.exceptions.CryptoFailedException: Unknown error: java.lang.IllegalStateException: Secure lock screen must be enabled to create keys requiring user authentication
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.encrypt(CipherStorageKeystoreRsaEcb.java:81)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.KeychainModule.setGenericPassword(KeychainModule.java:223)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.KeychainModule.setGenericPasswordForOptions(KeychainModule.java:252)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at java.lang.reflect.Method.invoke(Native Method)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at android.os.Handler.handleCallback(Handler.java:873)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at android.os.Looper.loop(Looper.java:193)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at java.lang.Thread.run(Thread.java:764)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: Secure lock screen must be enabled to create keys requiring user authentication
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize(AndroidKeyStoreKeyPairGeneratorSpi.java:349)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:697)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:438)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.generateKey(CipherStorageKeystoreRsaEcb.java:255)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.cipherStorage.CipherStorageBase.tryGenerateRegularSecurityKey(CipherStorageBase.java:445)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.cipherStorage.CipherStorageBase.generateKeyAndStoreUnderAlias(CipherStorageBase.java:421)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.innerEncryptedCredentials(CipherStorageKeystoreRsaEcb.java:197)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	at com.oblador.keychain.cipherStorage.CipherStorageKeystoreRsaEcb.encrypt(CipherStorageKeystoreRsaEcb.java:70)
09-14 10:51:59.621  4975  5035 E RNKeychainManager: 	... 12 more
```
I got this bug in my android device and on emulator. I don't know if this bug affects also iOS devices.

**Comment by JamesKEbert** [comment]
I can confirm I've observed this as well. IIRC, @jleach is working on a fix for this though?

**Comment by jleach** [comment]
Will look into it. It's an odd bug because the Create PIN screen has no biometrics code in it AFAIK. The following screen does as well as the Enter PIN screen. What version of Android and what device (so we know what flavour of Android).

**Comment by thiagoromanos** [comment]
> Will look into it. It's an odd bug because the Create PIN screen has no biometrics code in it AFAIK. The following screen does as well as the Enter PIN screen. What version of Android and what device (so we know what flavour of Android).

Both my phone and the emulator are running Android 9 (api level 28)

**Comment by thiagoromanos** [comment]
> Will look into it. It's an odd bug because the Create PIN screen has no biometrics code in it AFAIK.

That's another thing that I found a little weird... it asks me to use my fingerprint **before** I check the option to use biometrics as an authentication method. I thought that asking me after I check makes more sense.

**Comment by jleach** [comment]
@thiagoromanos Thanks. Android is a little tougher to config. We can use AES or RSA storage, one appears to require biometrics while the other it's optional. We'll figure it out. Thanks for the report.
