### ISSUE TITLE
BuildCMakeDebug Issue

### ISSUE THREAD

**Issue by PenguinTaro** [openwallet-foundation/bifold-wallet#908]
Hi folks, 

Recently while testing wallet app, I encounter an error while "yarn run android" command. I am attaching the screenshot for the following please let me know if anyone know the solution for the same. It was working earlier and has stop working since Friday. I have pasted the error logs
Thank you so much.
System used:
Windows 10.
Node 16.15.0
Redhat open-jdk 11.0.10.1

```
Task :hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a] FAILED
Caching disabled for task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]' because:
  Build cache is disabled
Task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]' is not up-to-date because:
  Task.upToDateWhen is false.
C/C++: starting build
C/C++: reading expected JSONs
C/C++: done reading expected JSONs
C/C++: executing build commands for targets that produce .so files or executables
C/C++: evaluate miniconfig
C/C++: evaluate library anoncredsreactnative (arm64-v8a)
C/C++: building target library anoncredsreactnative because no targets are specified.
C/C++: about to build targets anoncredsreactnative
C/C++: Executable : C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe
arguments :
-C
D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a
anoncredsreactnative
jvmArgs :


C/C++: Build anoncredsreactnative_arm64-v8a
C/C++: Executable : C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe
arguments :
-C
D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a
anoncredsreactnative
jvmArgs :


Starting process 'command 'C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe''. Working directory: D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android Command: C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe -C D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a anoncredsreactnative
Successfully started process 'command 'C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe''   
C/C++: ninja: error: mkdir(CMakeFiles/anoncredsreactnative.dir/D_/devika.kulkarni/hyperledgerAries/AriesBifold0.4/packages/legacy): No such file or directory
:hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a] (Thread[Execution worker Thread 2,5,main]) completed. Took 1.146 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
410 actionable tasks: 6 executed, 404 up-to-date
Watched directory hierarchies: [D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\android]

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a anoncredsreactnative}
  ninja: Entering directory `D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a'
  ninja: build stopped: .

  ninja: error: mkdir(CMakeFiles/anoncredsreactnative.dir/D_/devika.kulkarni/hyperledgerAries/AriesBifold0.4/packages/legacy): No such file or directory


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\devika.kulkarni\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a anoncredsreactnative}
  ninja: Entering directory `D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@hyperledger\anoncreds-react-native\android\.cxx\Debug\3e3z493y\arm64-v8a'
  ninja: build stopped: .

  ninja: error: mkdir(CMakeFiles/anoncredsreactnative.dir/D_/devika.kulkarni/hyperledgerAries/AriesBifold0.4/packages/legacy): No such file or directory


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org
BUILD FAILED in 3m 12s

    at makeError (D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\execa\index.js:174:9)    
    at D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
npm ERR! Lifecycle script `android` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: aries-bifold-app@0.0.1
npm ERR!   at location: D:\devika.kulkarni\hyperledgerAries\AriesBifold0.4\packages\legacy\app
```

**Comment by YEASIN49** [comment]
I am facing similar issues on ubuntu 22.4, node 16.15.0. Tried  some probable solution.
rm -rf ~/.gradle/caches/ 
./gradle clean
removed node_modules and  lock files and installed packages again
But nothing happens. 
The noticable thing is, I used the same files some days before and it was all fine then, but suddenly came to this issue.
The log I have from terminal might be helpful: 

```
Successfully started process 'command '/home/yeasin49/Android/Sdk/cmake/3.18.1/bin/ninja''
C/C++: ninja: Entering directory `/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/android/.cxx/Debug/727332o6/arm64-v8a'
C/C++: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:330:31: warning: ISO C++ requires field designators to be specified in declaration order; field 'is_predicate' will be initialized after field 'referent' [-Wreorder-init-list]
C/C++: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:329:47: note: previous initialization for field 'is_predicate' is here
C/C++: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:405:47: warning: ISO C++ requires field designators to be specified in declaration order; field 'is_predicate' will be initialized after field 'referent' [-Wreorder-init-list]
C/C++: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:404:63: note: previous initialization for field 'is_predicate' is here
C/C++: ld: error: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/native/mobile/android/arm64-v8a/libanoncreds.so: section header table goes past the end of the file: e_shoff = 0x920010
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)

> Task :hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a] FAILED
:hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a] (Thread[included builds,5,main]) completed. Took 6.596 secs.
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
425 actionable tasks: 401 executed, 24 up-to-date
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-localize/android/src/main/java/com/zoontek/rnlocalize/RNLocalizeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsPackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/yeasin49/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/android/.cxx/Debug/727332o6/arm64-v8a anoncredsreactnative}
  ninja: Entering directory `/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/android/.cxx/Debug/727332o6/arm64-v8a'
  [1/5] Building CXX object 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/anoncreds.cpp.o'
  [2/5] Building CXX object 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp.o'
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:330:31: warning: ISO C++ requires field designators to be specified in declaration order; field 'is_predicate' will be initialized after field 'referent' [-Wreorder-init-list]
                                .referent = referent.c_str(),
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:329:47: note: previous initialization for field 'is_predicate' is here
                                .is_predicate = isPredicate,
                                                ^~~~~~~~~~~
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:405:47: warning: ISO C++ requires field designators to be specified in declaration order; field 'is_predicate' will be initialized after field 'referent' [-Wreorder-init-list]
                                                .referent = ffiStr,
                                                ^~~~~~~~~~~~~~~~~~
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:404:63: note: previous initialization for field 'is_predicate' is here
                                                .is_predicate = isPredicate,
                                                                ^~~~~~~~~~~
  2 warnings generated.
  [3/5] Building CXX object 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/HostObject.cpp.o'
  [4/5] Building CXX object CMakeFiles/anoncredsreactnative.dir/cpp-adapter.cpp.o
  [5/5] Linking CXX shared library ../../../../build/intermediates/cxx/Debug/727332o6/obj/arm64-v8a/libanoncredsreactnative.so
  FAILED: ../../../../build/intermediates/cxx/Debug/727332o6/obj/arm64-v8a/libanoncredsreactnative.so 
  : && /home/yeasin49/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/yeasin49/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--gc-sections -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libanoncredsreactnative.so -o ../../../../build/intermediates/cxx/Debug/727332o6/obj/arm64-v8a/libanoncredsreactnative.so CMakeFiles/anoncredsreactnative.dir/cpp-adapter.cpp.o 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/HostObject.cpp.o' 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp.o' 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/anoncreds.cpp.o' -L/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/native/mobile/android/arm64-v8a -lanoncreds  /home/yeasin49/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/liblog.so  ../../../../build/react-native-0.66.5.aar/jni/arm64-v8a/libjsi.so  ../../../../build/react-native-0.66.5.aar/jni/arm64-v8a/libreactnativejni.so  ../../../../build/react-native-0.66.5.aar/jni/arm64-v8a/libfbjni.so  -landroid  -latomic -lm && :
  ld: error: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/native/mobile/android/arm64-v8a/libanoncreds.so: section header table goes past the end of the file: e_shoff = 0x920010
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 47m 54s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-localize/android/src/main/java/com/zoontek/rnlocalize/RNLocalizeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsPackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/VirtualView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hyperledger_anoncreds-react-native:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/yeasin49/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/android/.cxx/Debug/727332o6/arm64-v8a anoncredsreactnative}
  ninja: Entering directory `/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/android/.cxx/Debug/727332o6/arm64-v8a'
  [1/5] Building CXX object 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/anoncreds.cpp.o'
  [2/5] Building CXX object 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp.o'
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:330:31: warning: ISO C++ requires field designators to be specified in declaration order; field 'is_predicate' will be initialized after field 'referent' [-Wreorder-init-list]
                                .referent = referent.c_str(),
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:329:47: note: previous initialization for field 'is_predicate' is here
                                .is_predicate = isPredicate,
                                                ^~~~~~~~~~~
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:405:47: warning: ISO C++ requires field designators to be specified in declaration order; field 'is_predicate' will be initialized after field 'referent' [-Wreorder-init-list]
                                                .referent = ffiStr,
                                                ^~~~~~~~~~~~~~~~~~
  /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp:404:63: note: previous initialization for field 'is_predicate' is here
                                                .is_predicate = isPredicate,
                                                                ^~~~~~~~~~~
  2 warnings generated.
  [3/5] Building CXX object 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/HostObject.cpp.o'
  [4/5] Building CXX object CMakeFiles/anoncredsreactnative.dir/cpp-adapter.cpp.o
  [5/5] Linking CXX shared library ../../../../build/intermediates/cxx/Debug/727332o6/obj/arm64-v8a/libanoncredsreactnative.so
  FAILED: ../../../../build/intermediates/cxx/Debug/727332o6/obj/arm64-v8a/libanoncredsreactnative.so 
  : && /home/yeasin49/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/yeasin49/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--gc-sections -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libanoncredsreactnative.so -o ../../../../build/intermediates/cxx/Debug/727332o6/obj/arm64-v8a/libanoncredsreactnative.so CMakeFiles/anoncredsreactnative.dir/cpp-adapter.cpp.o 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/HostObject.cpp.o' 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/turboModuleUtility.cpp.o' 'CMakeFiles/anoncredsreactnative.dir/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/cpp/anoncreds.cpp.o' -L/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/native/mobile/android/arm64-v8a -lanoncreds  /home/yeasin49/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/liblog.so  ../../../../build/react-native-0.66.5.aar/jni/arm64-v8a/libjsi.so  ../../../../build/react-native-0.66.5.aar/jni/arm64-v8a/libreactnativejni.so  ../../../../build/react-native-0.66.5.aar/jni/arm64-v8a/libfbjni.so  -landroid  -latomic -lm && :
  ld: error: /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@hyperledger/anoncreds-react-native/native/mobile/android/arm64-v8a/libanoncreds.so: section header table goes past the end of the file: e_shoff = 0x920010
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 47m 54s

    at makeError (/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/execa/index.js:174:9)
    at /home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/yeasin49/Documents/Research/Asset-Transfer/aries-mobile-agent-react-native/packages/legacy/app/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```
